### PR TITLE
feat : Add a function to return to the list

### PR DESCRIPTION
**Pull request by YusunPark**
## Pull request checklist

**Please check if your PR meets the following requirements**

- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Tested with (`npm run dev`) and is working great
- [ ] Build tested with (`node build/build.js`) and no errors
- [ ] Double checked the two items above

## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring
- [ ] Documentation
- [x] Other (describe):

## Describe your Pull Request

pr 시 나오는 템플릿 수정했습니다.
- Check list를 java에 맞게 수정

## Additional content

*Any last words?* 🤣

### CODE REVIEW

**Review by kim-hyeon-gi — APPROVED** [review]
넵!

**Review by geeneve — APPROVED** [review]
확인했습니다!

**Review by Winter-gr — APPROVED** [review]
확인했습니다!

**Comment by Junwoo-1** [comment]
확인했습니다~

**Review by Junwoo-1 — APPROVED** [review]
확인했습니다!

**Review by BaeGayeon — APPROVED** [review]
수고하셨습니다!

**Pull request merged**
